---
- name: add rule in acl 
  hosts:
    - 10.200.3.1
  vars:
    - accessListName: "1"
  tasks:

    - name: Merge provided configuration with device configuration
      cisco.ios.ios_acls:
        config:
        - afi: ipv4
          acls:
          - name: "{{ accessListName }}"
            acl_type: standard
            aces:
            - grant: permit
              source:
                address: 10.30.12.81
            #- grant: deny
            #  source:
            #    address: 10.0.0.0 
            #    wildcard_bits: 0.0.0.255
        state: merged
